version: '2.1'
services:
  vnpay-payment-service-provider:
    #logging:
    #  driver: awslogs
    #  options:
    #    awslogs-region: ap-southeast-1
    #    awslogs-group: echo-service-provider
    #    awslogs-create-group: 'true'
    #    awslogs-multiline-pattern: '(INFO|DEBUG|ERROR|WARNNING)'
    build:
      context: ./
    environment:
      - PAYMENT_SERVICE_ENABLED=YES
      - LOG_LEVEL=debug
      - KAFKA_QUEUE_ENABLED=NO
      - PAYMENT_SERVICE_PROVIDER=VNPAY
      - PAYMENT_SERVICE_URI=http://sandbox.vnpayment.vn/paymentv2/vpcpay.html
      - PAYMENT_SERVICE_RETURN_URL=http://192.168.99.100:8060/payment/returnResult
      - PAYMENT_SERVICE_TMN_CODE=ONONPAY1
      - PAYMENT_SERVICE_SECURE_HASH_KEY=XBAPBEDCYMQBMCHQMTPPIPMOLGXXMAEL
    ports:
     - 8060:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10
    restart: always
  123pay-payment-service-provider:
    #logging:
    #  driver: awslogs
    #  options:
    #    awslogs-region: ap-southeast-1
    #    awslogs-group: echo-service-provider
    #    awslogs-create-group: 'true'
    #    awslogs-multiline-pattern: '(INFO|DEBUG|ERROR|WARNNING)'
    build:
      context: ./
    environment:
      - PAYMENT_SERVICE_ENABLED=YES
      - LOG_LEVEL=debug
      - KAFKA_QUEUE_ENABLED=NO
      - PAYMENT_SERVICE_PROVIDER=123PAY
      - PAYMENT_SERVICE_URI=https://sandbox.123pay.vn/miservice/createOrder1
      - PAYMENT_SERVICE_RETURN_URL=http://192.168.99.100:8070/payment/returnResult
      - PAYMENT_SERVICE_MERCHANT_CODE=MICODE
      - PAYMENT_SERVICE_PASSCODE=MIPASSCODE
      - PAYMENT_SERVICE_SECURE_HASH_KEY=MIKEY
    ports:
     - 8070:8000
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10
    restart: always
  cassandra-database:
    build:
      context: /projects/payment-sevice-provider-v2/services/cassandra-database
    ports:
     - 9042:9042
    healthcheck:
      test: ["CMD-SHELL", "netstat -an | grep 9042 | grep -i listen || exit 1"]
      interval: 5s
      retries: 10
    restart: always
  cassandra-migrations:
    build:
      context: /projects/payment-sevice-provider-v2/services/cassandra-cqlsh
    depends_on:
      cassandra-database:
        condition: service_healthy
    command: cqlsh --file=/opt/cassandra-database/create-tables.cql cassandra-database 9042
    volumes:
      - /projects/payment-sevice-provider-v2/services/cassandra-database:/opt/cassandra-database
  cassandra-admin:
    build:
      context: /projects/payment-sevice-provider-v2/services/cassandra-admin
      args:
        - "CASSANDRA_HOST_PRIMARY=cassandra-database"
        - "CASSANDRA_HOST_SECONDARY=cassandra-database"
    depends_on:
      cassandra-database:
        condition: service_healthy
    ports:
     - 8088:8088
    restart: always